name: Build AltSign

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [Win32, x64]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup VS Dev Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v4

    - name: runs get-source.cmd
      run: | 
        cd Dependencies/libimobiledevice-vs
        ./get-source.cmd
        cd "c:\vcpkg"; ./bootstrap-vcpkg.bat; vcpkg integrate install
        ls

    - name: Build solution
      run: msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:SolutionDir="${{github.workspace}}\\"

    - name: Build MSI
      run: DevEnv AltSign.vcxproj

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.configuration }}-${{ matrix.platform }}-build
        path: ${{ matrix.platform }}/${{ matrix.configuration }}/
